function [fitresult, gof] = createFit(n, FW, errors)
%CREATEFIT(N,FW,ERRORS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : n
%      Y Output: FW
%      Weights : errors
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Apr-2022 14:57:19


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( n, FW, errors );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'FW vs. n with errors', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'n', 'Interpreter', 'none' );
ylabel( 'FW', 'Interpreter', 'none' );
grid on


